-- Store the webhook HMAC secret as AES-256-GCM ciphertext rather than a
-- SHA-256 hash. The old `secret_hash` column could only be used as an HMAC
-- key (non-standard shape) and could not be decrypted back into the secret
-- handed to the subscriber. After this migration the processor decrypts
-- `secret_enc` and signs with `HMAC(raw_secret, body)` — matching the
-- industry convention (Stripe/GitHub/Shopify).

-- Add the encrypted-secret column (nullable until all legacy rows have been
-- regenerated by their owners).
ALTER TABLE "webhook_subscriptions" ADD COLUMN "secret_enc" BYTEA;

-- Mark every existing row as needing regeneration: its `secret_hash` is a
-- one-way hash and cannot be lifted into `secret_enc`. New rows default to
-- false (the fresh row already carries a decryptable secret).
ALTER TABLE "webhook_subscriptions"
  ADD COLUMN "needs_regeneration" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "webhook_subscriptions"
  ALTER COLUMN "needs_regeneration" SET DEFAULT false;

-- Allow `secret_hash` to be NULL so newly created subscriptions don't have
-- to populate the legacy column. A follow-up migration will drop the column
-- entirely once legacy rows have all been regenerated and set to null.
ALTER TABLE "webhook_subscriptions"
  ALTER COLUMN "secret_hash" DROP NOT NULL;
